### ISSUE TITLE
Issues running in azure pipeline

### ISSUE THREAD

**Issue by infinitejest69** [joaoopereira/dotnet-test-rerun#166] opened 2024-07-10 10:21 UTC
After a lot of fettling i got the tests running but the rerun feature just fails and i am not 100% sure why

pipeline yml exttract

```
  - task: PowerShell@2
        name: InstallTool
        inputs:
          targetType: 'inline'
          script: |
            dotnet new tool-manifest --name test-manifest --force && dotnet tool install dotnet-test-rerun
        condition: succeededOrFailed()

      - task: DotNetCoreCLI@2
        displayName: 'Run Tests'
        inputs:
          command: custom
          custom: test-rerun
          arguments: $(System.DefaultWorkingDirectory)/Test/bin/Debug/net8.0/Test.dll -v Normal --rerunMaxAttempts $(RerunAttempts)
        condition: succeededOrFailed()
```

This works to run tests but the rerun fails

```
NUnit Adapter 4.5.0.0: Test execution complete
Results File: /azp/_work/7/s/_container-agent-linux-638561900517755639_2024-07-10_10_07_30.trx

Total tests: 1064
     Passed: 1063
     Failed: 1
Test Run Failed.
 Total time: 3.3102 Minutes



Test Run Failed.

Exit code 1.
command: dotnet test /azp/_work/7/s/Test/bin/Debug/net8.0/Test.dll --logger "trx" -v "Normal" --results-directory "/azp/_work/7/s"
##[error]Error: The process '/usr/bin/dotnet' failed with exit code 1
Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Dotnet command failed with non-zero exit code on the following projects : [ '' ]
Finishing: Run Tests

```

**Comment by IgorMikhalev** [comment] 2024-07-10 10:44
This looks like a duplicate of #149 . 
Have you tried the same with the latest prerelease version or without setting the verbosity option?

**Comment by infinitejest69** [comment] 2024-07-10 10:51
After running again with logging set to diagnostic rather than normal the rerun was attempted but another test failed.
The second issue appears to be that it does not like the FQN with spaces that come from using an nunit test case source

```
Rerun attempt 1/2
Found Failed tests: dotnet.test.rerun.Domain.TestFilterCollection
Framework: net8.0
Rerun filter: FullyQualifiedName~TestAPI.Tests.PagesTests.TranslationJobPage Valid Page,Valid locale,Valid Variant
Microsoft (R) Test Execution Command Line Tool Version 17.10.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
An exception occurred while invoking executor 'executor://nunit3testexecutor/': Unexpected Word 'Valid' at position 63 in selection expression.
Stack trace:
   at NUnit.VisualStudio.TestAdapter.TestFilterConverter.TestFilterParser.Expect(Token[] valid) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\TestFilterConverter\TestFilterParser.cs:line 260
   at NUnit.VisualStudio.TestAdapter.TestFilterConverter.TestFilterParser.Parse(String input) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\TestFilterConverter\TestFilterParser.cs:line 65
   at NUnit.VisualStudio.TestAdapter.NUnitTestFilterBuilder.ConvertVsTestFilterToNUnitFilter(IVsTestFilter vsFilter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitTestFilterBuilder.cs:line 74
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 125
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Microsoft.TestPlatform.Common/ExtensionDecorators/SerialTestRunDecorator.cs:line 57
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/RunTestsWithSources.cs:line 115
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/BaseRunTests.cs:line 466


```

Example
```
 [TestCaseSource(nameof(TranslationJobsPageCases), Category = "TranslationJobs,3.3")]
  ```

**Closed** 2024-07-10 14:08 UTC
